Traceback (most recent call last):
  File "/Users/qianahunt/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/qianahunt/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/qianahunt/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/qianahunt/anaconda3/envs/jupyterbook/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/qianahunt/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/qianahunt/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/qianahunt/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Setting up the base and the catalog coordinates for CorrectAstrometry
base_coords = GetCoords("testdata/M101_daofind_f555w_acs_fk5.reg")
cat_coords = [M101_calibrators["RA"].values.tolist(), M101_calibrators["Dec"].values.tolist()]

# Running CorrectAstrometry
CorrectAstrometry(base_coords, cat_coords, returnshifts=True, savebasereg="testdata/M101_astrocorrect.reg")
------------------

----- stdout -----
Retrieving coordinates from testdata/M101_daofind_f555w_acs_fk5.reg
----- stdout -----
Median separation: 3.6742641485463844e-05
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mStdinNotImplementedError[0m                  Traceback (most recent call last)
Cell [0;32mIn[3], line 6[0m
[1;32m      3[0m cat_coords [38;5;241m=[39m [M101_calibrators[[38;5;124m"[39m[38;5;124mRA[39m[38;5;124m"[39m][38;5;241m.[39mvalues[38;5;241m.[39mtolist(), M101_calibrators[[38;5;124m"[39m[38;5;124mDec[39m[38;5;124m"[39m][38;5;241m.[39mvalues[38;5;241m.[39mtolist()]
[1;32m      5[0m [38;5;66;03m# Running CorrectAstrometry[39;00m
[0;32m----> 6[0m [43mCorrectAstrometry[49m[43m([49m[43mbase_coords[49m[43m,[49m[43m [49m[43mcat_coords[49m[43m,[49m[43m [49m[43mreturnshifts[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m,[49m[43m [49m[43msavebasereg[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mtestdata/M101_astrocorrect.reg[39;49m[38;5;124;43m"[39;49m[43m)[49m

File [0;32m~/Desktop/Research/JupyterBooks/xrbid_guide/pyfiles/Align.py:313[0m, in [0;36mCorrectAstrometry[0;34m(base_coords, cat_coords, autoresid, returnshifts, returncoords, savebasereg)[0m
[1;32m    311[0m [38;5;66;03m# Request user to input minimum and maximum separation of "good sources"[39;00m
[1;32m    312[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mMedian separation:[39m[38;5;124m"[39m, median(separation[38;5;241m.[39mdeg))
[0;32m--> 313[0m minsep, maxsep [38;5;241m=[39m [38;5;28;43minput[39;49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mInput min and max separation:[39;49m[38;5;124;43m"[39;49m[43m)[49m[38;5;241m.[39msplit([38;5;124m"[39m[38;5;124m,[39m[38;5;124m"[39m)
[1;32m    314[0m minsep [38;5;241m=[39m [38;5;28mfloat[39m(minsep)
[1;32m    315[0m maxsep [38;5;241m=[39m [38;5;28mfloat[39m(maxsep)

File [0;32m~/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/ipykernel/kernelbase.py:1281[0m, in [0;36mKernel.raw_input[0;34m(self, prompt)[0m
[1;32m   1279[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_allow_stdin:
[1;32m   1280[0m     msg [38;5;241m=[39m [38;5;124m"[39m[38;5;124mraw_input was called, but this frontend does not support input requests.[39m[38;5;124m"[39m
[0;32m-> 1281[0m     [38;5;28;01mraise[39;00m StdinNotImplementedError(msg)
[1;32m   1282[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_input_request(
[1;32m   1283[0m     [38;5;28mstr[39m(prompt),
[1;32m   1284[0m     [38;5;28mself[39m[38;5;241m.[39m_parent_ident[[38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m],
[1;32m   1285[0m     [38;5;28mself[39m[38;5;241m.[39mget_parent([38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m),
[1;32m   1286[0m     password[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[1;32m   1287[0m )

[0;31mStdinNotImplementedError[0m: raw_input was called, but this frontend does not support input requests.

