Traceback (most recent call last):
  File "/Users/qianahunt/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/qianahunt/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/qianahunt/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/qianahunt/anaconda3/envs/jupyterbook/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/qianahunt/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/qianahunt/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/qianahunt/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib
import matplotlib.pyplot as plt
from astropy.wcs import WCS # defining the coordinate system, e.g. RA/Dec
from astropy.io import fits

cd("../fits")
hdu = fits.open('M101_acs_wfc_f435w_example.fits')
display(hdu.info()) # Display the hdu info to get more information about what it contains

# Setting up the figure
plt.figure(figsize=(6,6))

# hdu['SCI'].header usually contains info needed to set up the image projection
# But you may need to check your specific hdu file
ax = plt.subplot(projection=WCS(hdu['SCI',1].header))
plt.imshow(hdu['SCI',1].data, cmap="gray", origin="lower",
          norm=matplotlib.colors.Normalize(vmin=-0.05, vmax=.5))
plt.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 6[0m
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mastropy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mwcs[39;00m [38;5;28;01mimport[39;00m WCS [38;5;66;03m# defining the coordinate system, e.g. RA/Dec[39;00m
[1;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mastropy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mio[39;00m [38;5;28;01mimport[39;00m fits
[0;32m----> 6[0m [43mcd[49m([38;5;124m"[39m[38;5;124m../fits[39m[38;5;124m"[39m)
[1;32m      7[0m hdu [38;5;241m=[39m fits[38;5;241m.[39mopen([38;5;124m'[39m[38;5;124mM101_acs_wfc_f435w_example.fits[39m[38;5;124m'[39m)
[1;32m      8[0m display(hdu[38;5;241m.[39minfo()) [38;5;66;03m# Display the hdu info to get more information about what it contains[39;00m

[0;31mNameError[0m: name 'cd' is not defined

